server:
  port: 8081
  servlet:
    context-path: /eps
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eps
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:com/mxl/eps/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl